name: test-repolinter-action
on:
  push:
    branches:
      - master
      - main
      - trunk
      - develop

jobs:
  repolint:
    name: repolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v2
      - name: Run Repolinter
        uses: repolinter-action@v1
        with:
          config-url: https://raw.githubusercontent.com/aperture-science-incorporated/.github/master/repolinter-newrelic-communityplus.json
          output-type: issue
