name: test-repolinter-action
on:
  push:
    branches:
      - master
      - main
      - trunk
      - develop

jobs:
  repolint:
    name: repolint
    runs-on: ubuntu-latest
    steps:
      - name: Test Default Branch
        id: default-branch
        uses: actions/github-script@v2
        with:
          script: |
            const data = await github.repos.get(context.repo)
            core.debug(JSON.stringify(data))
            core.debug(JSON.stringify(context))
            return data.data && data.data["default_branch"] === context.ref.split('/').slice(-1)[0]
      - name: Checkout self
        if: ${{ steps.default-branch.outputs.result == 'true' }}
        uses: actions/checkout@v2
      - name: Run Repolinter
        if: ${{ steps.default-branch.outputs.result == 'true' }}
        uses: newrelic/repolinter-action@v1
        with:
          config_url: https://raw.githubusercontent.com/aperture-science-incorporated/.github/master/repolinter-newrelic-communityplus.json
          output_type: issue
